### ISSUE TITLE
Lag spikes

### ISSUE THREAD

**Issue by RohitKushvaha01** [dingyi222666/TreeView#13]
Hello,

I recently switched to using your tree view library in my app [Karbon](https://github.com/Xed-Editor/Xed-Editor), as my own implementation had some layout issues. While your library resolves those, I’ve noticed significant lag when opening directories, especially when double-clicking on a folder. It seems to trigger excessive loading or processing, which causes noticeable performance drops.

I suspect this could be an issue with how I’ve implemented the library in my project. Could you guide me on optimizing it to avoid these lags? I’d appreciate any advice or suggestions you can provide.

Thank you!

**Comment by dingyi222666** [comment]
Hello! Could you provide me with a minimal reproducible example so that I can diagnose this issue?

**Comment by RohitKushvaha01** [comment]
> Hello! Could you provide me with a minimal reproducible example so that I can diagnose this issue?

Sorry for the issue. It was a problem with my implementation, but I’ve fixed it.

**Comment by dingyi222666** [comment]
Well, still thank you for your issue.



---Original---
From: "Rohit ***@***.***&gt;
Date: Mon, Nov 18, 2024 16:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dingyi222666/TreeView] Lag spikes (Issue #13)




  
Hello! Could you provide me with a minimal reproducible example so that I can diagnose this issue?
  
Sorry for the issue. It was a problem with my implementation, but I’ve fixed it.
